Repository selfdefined/web-app, pull requests merged in 2020-06, with the labels that each got.

#196 Propose definition for Digital Blackface
  11ty/definitions/digital-blackface.md
Labels: Type · Definitions

#192 Feature/rss feed
  .eleventy.js
  11ty/_data/metadata.json
  11ty/_includes/layouts/base.njk
  11ty/definitions/-misia.md
  11ty/definitions/derpy.md
  11ty/feed.njk
  assets/css/structures/_footer.scss
  package-lock.json
  package.json
Labels: Status · Needs Review, Type · Feature Request, Type · Frontend

#212 fix: also run Actions CI on Pull Request events
  .github/workflows/main.yml
Labels: Type · DX

#221 [WIP] Proposed Definition: Boogaloo
  11ty/definitions/boogaloo.md
Labels: Type · Definitions

#201 adds optical allyship
  11ty/definitions/optical-allyship.md
Labels: Status · Needs Info

#243 Added preconnect/dns-prefetch hints for Typekit CSS resources.
  11ty/_includes/layouts/base.njk
Labels: Status · Needs Review

#250 fixed the typo in the README.md for Contributor Covenant spelling
  README.md
Labels: Status · Needs Info
