Repository selfdefined/web-app, pull requests merged in 2020-10, with the labels that each got.

#260 Create definition for ADHD
  11ty/definitions/adhd.md
Labels: Status · In Progress

#344 Replace expired Slack link in Readme
  CONTRIBUTING.md
Labels: Type · Bug, Type · Documentation

#350 [pt_PT] Translates capatismo, cisgenero, transgenero #279
  11ty/definitions/ableism.md
  11ty/definitions/pt_PT/capacitismo.md
  11ty/definitions/pt_PT/cisgenero.md
  11ty/definitions/pt_PT/transgenero.md
Labels: Language · pt_PT, Type · Translations
